fragment ConfigParts on Config {
  __typename
  logo
  nav {
    __typename
    label
    href
  }
  heroHome {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroServicios {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroNosotros {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroContacto {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroImagenes
}

fragment FooterParts on Footer {
  __typename
  descripcion
  copyright
  facebook
  serviciosLinks {
    __typename
    label
    href
  }
  empresaLinks {
    __typename
    label
    href
  }
  legalLinksIzquierda {
    __typename
    label
    href
  }
  legalLinksDerecha {
    __typename
    label
    href
  }
}

fragment HomeParts on Home {
  __typename
  propuestaTag
  propuestaTitulo
  propuestaSubtitulo
  propuestaItems
  enfoqueHeader
  enfoqueSubtitulo
  enfoqueCards {
    __typename
    emoji
    titulo
    descripcion
  }
  crecimientoTitulo
  crecimientoSubtitulo
  crecimientoCards {
    __typename
    titulo
    descripcion
    imagenes
  }
  procesoHeader
  procesoSubtitulo
  procesoSteps {
    __typename
    titulo
    descripcion
  }
  innovacionHeader
  innovacionSubtitulo
  innovacionFeatures {
    __typename
    emoji
    titulo
    descripcion
  }
  innovacionImagenes
}

fragment ServiciosParts on Servicios {
  __typename
  introTitulo
  introSubtitulo
  introDesc
  introPorqueTitulo
  introPorqueSubtitulo
  introPorqueDesc
  nuestrosServiciosTitulo
  nuestrosServiciosSubtitulo
  servicios {
    __typename
    titulo
    descripcion
    items
  }
  integralTitulo
  integralSubtitulo
  integralImagenPrincipal
  integralCards {
    __typename
    titulo
    descripcion
  }
  herramientasTitulo
  herramientasSubtitulo
  herramientasCategorias {
    __typename
    categoria
    color
    herramientas {
      __typename
      nombre
      descripcion
      emoji
      bg
    }
  }
  faqItems {
    __typename
    pregunta
    respuesta
  }
}

fragment NosotrosParts on Nosotros {
  __typename
  quienesTag
  quienesTitulo
  quienesDesc1
  quienesDesc2
  quienesImagen
  statProyectos
  statSatisfaccion
  statAnios
  misionTitulo
  misionDesc
  visionTitulo
  visionDesc
  equipoSubtitulo
  porqueTag
  porqueTitulo
  porqueSubtitulo
  porqueItems
  teamMembers {
    __typename
    nombre
    rol
    descripcion
    foto
    linkedin
  }
}

fragment LegalParts on Legal {
  __typename
  privacidad {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
  cookies {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
  terminos {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
}

fragment ContactoParts on Contacto {
  __typename
  panelTag
  panelTitulo
  panelDescripcion
  panelItems
  email
  whatsapp
  direccion
  instagram
  linkedin
}
