//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  config: Config;
  configConnection: ConfigConnection;
  footer: Footer;
  footerConnection: FooterConnection;
  home: Home;
  homeConnection: HomeConnection;
  servicios: Servicios;
  serviciosConnection: ServiciosConnection;
  nosotros: Nosotros;
  nosotrosConnection: NosotrosConnection;
  legal: Legal;
  legalConnection: LegalConnection;
  contacto: Contacto;
  contactoConnection: ContactoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryServiciosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiciosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
};


export type QueryNosotrosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNosotrosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NosotrosFilter>;
};


export type QueryLegalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLegalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LegalFilter>;
};


export type QueryContactoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
};

export type DocumentFilter = {
  config?: InputMaybe<ConfigFilter>;
  footer?: InputMaybe<FooterFilter>;
  home?: InputMaybe<HomeFilter>;
  servicios?: InputMaybe<ServiciosFilter>;
  nosotros?: InputMaybe<NosotrosFilter>;
  legal?: InputMaybe<LegalFilter>;
  contacto?: InputMaybe<ContactoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Config | Footer | Home | Servicios | Nosotros | Legal | Contacto | Folder;

export type ConfigNav = {
  __typename?: 'ConfigNav';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type ConfigHeroHome = {
  __typename?: 'ConfigHeroHome';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroServicios = {
  __typename?: 'ConfigHeroServicios';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroNosotros = {
  __typename?: 'ConfigHeroNosotros';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroContacto = {
  __typename?: 'ConfigHeroContacto';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Config = Node & Document & {
  __typename?: 'Config';
  logo?: Maybe<Scalars['String']['output']>;
  nav?: Maybe<Array<Maybe<ConfigNav>>>;
  heroHome?: Maybe<ConfigHeroHome>;
  heroServicios?: Maybe<ConfigHeroServicios>;
  heroNosotros?: Maybe<ConfigHeroNosotros>;
  heroContacto?: Maybe<ConfigHeroContacto>;
  heroImagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigNavFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ConfigHeroHomeFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroServiciosFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroNosotrosFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroContactoFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigFilter = {
  logo?: InputMaybe<ImageFilter>;
  nav?: InputMaybe<ConfigNavFilter>;
  heroHome?: InputMaybe<ConfigHeroHomeFilter>;
  heroServicios?: InputMaybe<ConfigHeroServiciosFilter>;
  heroNosotros?: InputMaybe<ConfigHeroNosotrosFilter>;
  heroContacto?: InputMaybe<ConfigHeroContactoFilter>;
  heroImagenes?: InputMaybe<ImageFilter>;
};

export type ConfigConnectionEdges = {
  __typename?: 'ConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Config>;
};

export type ConfigConnection = Connection & {
  __typename?: 'ConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigConnectionEdges>>>;
};

export type FooterServiciosLinks = {
  __typename?: 'FooterServiciosLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type FooterEmpresaLinks = {
  __typename?: 'FooterEmpresaLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type FooterLegalLinksIzquierda = {
  __typename?: 'FooterLegalLinksIzquierda';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type FooterLegalLinksDerecha = {
  __typename?: 'FooterLegalLinksDerecha';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  descripcion?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  serviciosLinks?: Maybe<Array<Maybe<FooterServiciosLinks>>>;
  empresaLinks?: Maybe<Array<Maybe<FooterEmpresaLinks>>>;
  legalLinksIzquierda?: Maybe<Array<Maybe<FooterLegalLinksIzquierda>>>;
  legalLinksDerecha?: Maybe<Array<Maybe<FooterLegalLinksDerecha>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterServiciosLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterEmpresaLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterLegalLinksIzquierdaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterLegalLinksDerechaFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type FooterFilter = {
  descripcion?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  serviciosLinks?: InputMaybe<FooterServiciosLinksFilter>;
  empresaLinks?: InputMaybe<FooterEmpresaLinksFilter>;
  legalLinksIzquierda?: InputMaybe<FooterLegalLinksIzquierdaFilter>;
  legalLinksDerecha?: InputMaybe<FooterLegalLinksDerechaFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type HomeEnfoqueCards = {
  __typename?: 'HomeEnfoqueCards';
  emoji?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type HomeCrecimientoCards = {
  __typename?: 'HomeCrecimientoCards';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  imagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeProcesoSteps = {
  __typename?: 'HomeProcesoSteps';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type HomeInnovacionFeatures = {
  __typename?: 'HomeInnovacionFeatures';
  emoji?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  propuestaTag?: Maybe<Scalars['String']['output']>;
  propuestaTitulo?: Maybe<Scalars['String']['output']>;
  propuestaSubtitulo?: Maybe<Scalars['String']['output']>;
  propuestaItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  enfoqueHeader?: Maybe<Scalars['String']['output']>;
  enfoqueSubtitulo?: Maybe<Scalars['String']['output']>;
  enfoqueCards?: Maybe<Array<Maybe<HomeEnfoqueCards>>>;
  crecimientoTitulo?: Maybe<Scalars['String']['output']>;
  crecimientoSubtitulo?: Maybe<Scalars['String']['output']>;
  crecimientoCards?: Maybe<Array<Maybe<HomeCrecimientoCards>>>;
  procesoHeader?: Maybe<Scalars['String']['output']>;
  procesoSubtitulo?: Maybe<Scalars['String']['output']>;
  procesoSteps?: Maybe<Array<Maybe<HomeProcesoSteps>>>;
  innovacionHeader?: Maybe<Scalars['String']['output']>;
  innovacionSubtitulo?: Maybe<Scalars['String']['output']>;
  innovacionFeatures?: Maybe<Array<Maybe<HomeInnovacionFeatures>>>;
  innovacionImagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeEnfoqueCardsFilter = {
  emoji?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeCrecimientoCardsFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  imagenes?: InputMaybe<ImageFilter>;
};

export type HomeProcesoStepsFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeInnovacionFeaturesFilter = {
  emoji?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  propuestaTag?: InputMaybe<StringFilter>;
  propuestaTitulo?: InputMaybe<StringFilter>;
  propuestaSubtitulo?: InputMaybe<StringFilter>;
  propuestaItems?: InputMaybe<StringFilter>;
  enfoqueHeader?: InputMaybe<StringFilter>;
  enfoqueSubtitulo?: InputMaybe<StringFilter>;
  enfoqueCards?: InputMaybe<HomeEnfoqueCardsFilter>;
  crecimientoTitulo?: InputMaybe<StringFilter>;
  crecimientoSubtitulo?: InputMaybe<StringFilter>;
  crecimientoCards?: InputMaybe<HomeCrecimientoCardsFilter>;
  procesoHeader?: InputMaybe<StringFilter>;
  procesoSubtitulo?: InputMaybe<StringFilter>;
  procesoSteps?: InputMaybe<HomeProcesoStepsFilter>;
  innovacionHeader?: InputMaybe<StringFilter>;
  innovacionSubtitulo?: InputMaybe<StringFilter>;
  innovacionFeatures?: InputMaybe<HomeInnovacionFeaturesFilter>;
  innovacionImagenes?: InputMaybe<ImageFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type ServiciosServicios = {
  __typename?: 'ServiciosServicios';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ServiciosFaqItems = {
  __typename?: 'ServiciosFaqItems';
  pregunta?: Maybe<Scalars['String']['output']>;
  respuesta?: Maybe<Scalars['String']['output']>;
};

export type Servicios = Node & Document & {
  __typename?: 'Servicios';
  introTitulo?: Maybe<Scalars['String']['output']>;
  introSubtitulo?: Maybe<Scalars['String']['output']>;
  introDesc?: Maybe<Scalars['String']['output']>;
  introPorqueTitulo?: Maybe<Scalars['String']['output']>;
  introPorqueSubtitulo?: Maybe<Scalars['String']['output']>;
  introPorqueDesc?: Maybe<Scalars['String']['output']>;
  nuestrosServiciosTitulo?: Maybe<Scalars['String']['output']>;
  nuestrosServiciosSubtitulo?: Maybe<Scalars['String']['output']>;
  servicios?: Maybe<Array<Maybe<ServiciosServicios>>>;
  integralTitulo?: Maybe<Scalars['String']['output']>;
  integralSubtitulo?: Maybe<Scalars['String']['output']>;
  integralImagenPrincipal?: Maybe<Scalars['String']['output']>;
  herramientasTitulo?: Maybe<Scalars['String']['output']>;
  herramientasSubtitulo?: Maybe<Scalars['String']['output']>;
  faqItems?: Maybe<Array<Maybe<ServiciosFaqItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiciosServiciosFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type ServiciosFaqItemsFilter = {
  pregunta?: InputMaybe<StringFilter>;
  respuesta?: InputMaybe<StringFilter>;
};

export type ServiciosFilter = {
  introTitulo?: InputMaybe<StringFilter>;
  introSubtitulo?: InputMaybe<StringFilter>;
  introDesc?: InputMaybe<StringFilter>;
  introPorqueTitulo?: InputMaybe<StringFilter>;
  introPorqueSubtitulo?: InputMaybe<StringFilter>;
  introPorqueDesc?: InputMaybe<StringFilter>;
  nuestrosServiciosTitulo?: InputMaybe<StringFilter>;
  nuestrosServiciosSubtitulo?: InputMaybe<StringFilter>;
  servicios?: InputMaybe<ServiciosServiciosFilter>;
  integralTitulo?: InputMaybe<StringFilter>;
  integralSubtitulo?: InputMaybe<StringFilter>;
  integralImagenPrincipal?: InputMaybe<ImageFilter>;
  herramientasTitulo?: InputMaybe<StringFilter>;
  herramientasSubtitulo?: InputMaybe<StringFilter>;
  faqItems?: InputMaybe<ServiciosFaqItemsFilter>;
};

export type ServiciosConnectionEdges = {
  __typename?: 'ServiciosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Servicios>;
};

export type ServiciosConnection = Connection & {
  __typename?: 'ServiciosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiciosConnectionEdges>>>;
};

export type NosotrosTeamMembers = {
  __typename?: 'NosotrosTeamMembers';
  nombre?: Maybe<Scalars['String']['output']>;
  rol?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
};

export type Nosotros = Node & Document & {
  __typename?: 'Nosotros';
  quienesTag?: Maybe<Scalars['String']['output']>;
  quienesTitulo?: Maybe<Scalars['String']['output']>;
  quienesDesc1?: Maybe<Scalars['String']['output']>;
  quienesDesc2?: Maybe<Scalars['String']['output']>;
  quienesImagen?: Maybe<Scalars['String']['output']>;
  statProyectos?: Maybe<Scalars['String']['output']>;
  statSatisfaccion?: Maybe<Scalars['String']['output']>;
  statAnios?: Maybe<Scalars['String']['output']>;
  misionTitulo?: Maybe<Scalars['String']['output']>;
  misionDesc?: Maybe<Scalars['String']['output']>;
  visionTitulo?: Maybe<Scalars['String']['output']>;
  visionDesc?: Maybe<Scalars['String']['output']>;
  equipoSubtitulo?: Maybe<Scalars['String']['output']>;
  porqueTag?: Maybe<Scalars['String']['output']>;
  porqueTitulo?: Maybe<Scalars['String']['output']>;
  porqueSubtitulo?: Maybe<Scalars['String']['output']>;
  porqueItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  teamMembers?: Maybe<Array<Maybe<NosotrosTeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NosotrosTeamMembersFilter = {
  nombre?: InputMaybe<StringFilter>;
  rol?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type NosotrosFilter = {
  quienesTag?: InputMaybe<StringFilter>;
  quienesTitulo?: InputMaybe<StringFilter>;
  quienesDesc1?: InputMaybe<StringFilter>;
  quienesDesc2?: InputMaybe<StringFilter>;
  quienesImagen?: InputMaybe<ImageFilter>;
  statProyectos?: InputMaybe<StringFilter>;
  statSatisfaccion?: InputMaybe<StringFilter>;
  statAnios?: InputMaybe<StringFilter>;
  misionTitulo?: InputMaybe<StringFilter>;
  misionDesc?: InputMaybe<StringFilter>;
  visionTitulo?: InputMaybe<StringFilter>;
  visionDesc?: InputMaybe<StringFilter>;
  equipoSubtitulo?: InputMaybe<StringFilter>;
  porqueTag?: InputMaybe<StringFilter>;
  porqueTitulo?: InputMaybe<StringFilter>;
  porqueSubtitulo?: InputMaybe<StringFilter>;
  porqueItems?: InputMaybe<StringFilter>;
  teamMembers?: InputMaybe<NosotrosTeamMembersFilter>;
};

export type NosotrosConnectionEdges = {
  __typename?: 'NosotrosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Nosotros>;
};

export type NosotrosConnection = Connection & {
  __typename?: 'NosotrosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NosotrosConnectionEdges>>>;
};

export type LegalPrivacidadBloques = {
  __typename?: 'LegalPrivacidadBloques';
  titulo?: Maybe<Scalars['String']['output']>;
  contenido?: Maybe<Scalars['String']['output']>;
};

export type LegalPrivacidad = {
  __typename?: 'LegalPrivacidad';
  bloques?: Maybe<Array<Maybe<LegalPrivacidadBloques>>>;
};

export type LegalCookiesBloques = {
  __typename?: 'LegalCookiesBloques';
  titulo?: Maybe<Scalars['String']['output']>;
  contenido?: Maybe<Scalars['String']['output']>;
};

export type LegalCookies = {
  __typename?: 'LegalCookies';
  bloques?: Maybe<Array<Maybe<LegalCookiesBloques>>>;
};

export type LegalTerminosBloques = {
  __typename?: 'LegalTerminosBloques';
  titulo?: Maybe<Scalars['String']['output']>;
  contenido?: Maybe<Scalars['String']['output']>;
};

export type LegalTerminos = {
  __typename?: 'LegalTerminos';
  bloques?: Maybe<Array<Maybe<LegalTerminosBloques>>>;
};

export type Legal = Node & Document & {
  __typename?: 'Legal';
  privacidad?: Maybe<LegalPrivacidad>;
  cookies?: Maybe<LegalCookies>;
  terminos?: Maybe<LegalTerminos>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type LegalPrivacidadBloquesFilter = {
  titulo?: InputMaybe<StringFilter>;
  contenido?: InputMaybe<StringFilter>;
};

export type LegalPrivacidadFilter = {
  bloques?: InputMaybe<LegalPrivacidadBloquesFilter>;
};

export type LegalCookiesBloquesFilter = {
  titulo?: InputMaybe<StringFilter>;
  contenido?: InputMaybe<StringFilter>;
};

export type LegalCookiesFilter = {
  bloques?: InputMaybe<LegalCookiesBloquesFilter>;
};

export type LegalTerminosBloquesFilter = {
  titulo?: InputMaybe<StringFilter>;
  contenido?: InputMaybe<StringFilter>;
};

export type LegalTerminosFilter = {
  bloques?: InputMaybe<LegalTerminosBloquesFilter>;
};

export type LegalFilter = {
  privacidad?: InputMaybe<LegalPrivacidadFilter>;
  cookies?: InputMaybe<LegalCookiesFilter>;
  terminos?: InputMaybe<LegalTerminosFilter>;
};

export type LegalConnectionEdges = {
  __typename?: 'LegalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Legal>;
};

export type LegalConnection = Connection & {
  __typename?: 'LegalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LegalConnectionEdges>>>;
};

export type Contacto = Node & Document & {
  __typename?: 'Contacto';
  panelTag?: Maybe<Scalars['String']['output']>;
  panelTitulo?: Maybe<Scalars['String']['output']>;
  panelDescripcion?: Maybe<Scalars['String']['output']>;
  panelItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  email?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  direccion?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactoFilter = {
  panelTag?: InputMaybe<StringFilter>;
  panelTitulo?: InputMaybe<StringFilter>;
  panelDescripcion?: InputMaybe<StringFilter>;
  panelItems?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
  direccion?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type ContactoConnectionEdges = {
  __typename?: 'ContactoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacto>;
};

export type ContactoConnection = Connection & {
  __typename?: 'ContactoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConfig: Config;
  createConfig: Config;
  updateFooter: Footer;
  createFooter: Footer;
  updateHome: Home;
  createHome: Home;
  updateServicios: Servicios;
  createServicios: Servicios;
  updateNosotros: Nosotros;
  createNosotros: Nosotros;
  updateLegal: Legal;
  createLegal: Legal;
  updateContacto: Contacto;
  createContacto: Contacto;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationCreateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationCreateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationUpdateNosotrosArgs = {
  relativePath: Scalars['String']['input'];
  params: NosotrosMutation;
};


export type MutationCreateNosotrosArgs = {
  relativePath: Scalars['String']['input'];
  params: NosotrosMutation;
};


export type MutationUpdateLegalArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalMutation;
};


export type MutationCreateLegalArgs = {
  relativePath: Scalars['String']['input'];
  params: LegalMutation;
};


export type MutationUpdateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};


export type MutationCreateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};

export type DocumentUpdateMutation = {
  config?: InputMaybe<ConfigMutation>;
  footer?: InputMaybe<FooterMutation>;
  home?: InputMaybe<HomeMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  nosotros?: InputMaybe<NosotrosMutation>;
  legal?: InputMaybe<LegalMutation>;
  contacto?: InputMaybe<ContactoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  config?: InputMaybe<ConfigMutation>;
  footer?: InputMaybe<FooterMutation>;
  home?: InputMaybe<HomeMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  nosotros?: InputMaybe<NosotrosMutation>;
  legal?: InputMaybe<LegalMutation>;
  contacto?: InputMaybe<ContactoMutation>;
};

export type ConfigNavMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigHeroHomeMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroServiciosMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroNosotrosMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroContactoMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigMutation = {
  logo?: InputMaybe<Scalars['String']['input']>;
  nav?: InputMaybe<Array<InputMaybe<ConfigNavMutation>>>;
  heroHome?: InputMaybe<ConfigHeroHomeMutation>;
  heroServicios?: InputMaybe<ConfigHeroServiciosMutation>;
  heroNosotros?: InputMaybe<ConfigHeroNosotrosMutation>;
  heroContacto?: InputMaybe<ConfigHeroContactoMutation>;
  heroImagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FooterServiciosLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterEmpresaLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLegalLinksIzquierdaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterLegalLinksDerechaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type FooterMutation = {
  descripcion?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  serviciosLinks?: InputMaybe<Array<InputMaybe<FooterServiciosLinksMutation>>>;
  empresaLinks?: InputMaybe<Array<InputMaybe<FooterEmpresaLinksMutation>>>;
  legalLinksIzquierda?: InputMaybe<Array<InputMaybe<FooterLegalLinksIzquierdaMutation>>>;
  legalLinksDerecha?: InputMaybe<Array<InputMaybe<FooterLegalLinksDerechaMutation>>>;
};

export type HomeEnfoqueCardsMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeCrecimientoCardsMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  imagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeProcesoStepsMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeInnovacionFeaturesMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  propuestaTag?: InputMaybe<Scalars['String']['input']>;
  propuestaTitulo?: InputMaybe<Scalars['String']['input']>;
  propuestaSubtitulo?: InputMaybe<Scalars['String']['input']>;
  propuestaItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  enfoqueHeader?: InputMaybe<Scalars['String']['input']>;
  enfoqueSubtitulo?: InputMaybe<Scalars['String']['input']>;
  enfoqueCards?: InputMaybe<Array<InputMaybe<HomeEnfoqueCardsMutation>>>;
  crecimientoTitulo?: InputMaybe<Scalars['String']['input']>;
  crecimientoSubtitulo?: InputMaybe<Scalars['String']['input']>;
  crecimientoCards?: InputMaybe<Array<InputMaybe<HomeCrecimientoCardsMutation>>>;
  procesoHeader?: InputMaybe<Scalars['String']['input']>;
  procesoSubtitulo?: InputMaybe<Scalars['String']['input']>;
  procesoSteps?: InputMaybe<Array<InputMaybe<HomeProcesoStepsMutation>>>;
  innovacionHeader?: InputMaybe<Scalars['String']['input']>;
  innovacionSubtitulo?: InputMaybe<Scalars['String']['input']>;
  innovacionFeatures?: InputMaybe<Array<InputMaybe<HomeInnovacionFeaturesMutation>>>;
  innovacionImagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiciosServiciosMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiciosFaqItemsMutation = {
  pregunta?: InputMaybe<Scalars['String']['input']>;
  respuesta?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosMutation = {
  introTitulo?: InputMaybe<Scalars['String']['input']>;
  introSubtitulo?: InputMaybe<Scalars['String']['input']>;
  introDesc?: InputMaybe<Scalars['String']['input']>;
  introPorqueTitulo?: InputMaybe<Scalars['String']['input']>;
  introPorqueSubtitulo?: InputMaybe<Scalars['String']['input']>;
  introPorqueDesc?: InputMaybe<Scalars['String']['input']>;
  nuestrosServiciosTitulo?: InputMaybe<Scalars['String']['input']>;
  nuestrosServiciosSubtitulo?: InputMaybe<Scalars['String']['input']>;
  servicios?: InputMaybe<Array<InputMaybe<ServiciosServiciosMutation>>>;
  integralTitulo?: InputMaybe<Scalars['String']['input']>;
  integralSubtitulo?: InputMaybe<Scalars['String']['input']>;
  integralImagenPrincipal?: InputMaybe<Scalars['String']['input']>;
  herramientasTitulo?: InputMaybe<Scalars['String']['input']>;
  herramientasSubtitulo?: InputMaybe<Scalars['String']['input']>;
  faqItems?: InputMaybe<Array<InputMaybe<ServiciosFaqItemsMutation>>>;
};

export type NosotrosTeamMembersMutation = {
  nombre?: InputMaybe<Scalars['String']['input']>;
  rol?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type NosotrosMutation = {
  quienesTag?: InputMaybe<Scalars['String']['input']>;
  quienesTitulo?: InputMaybe<Scalars['String']['input']>;
  quienesDesc1?: InputMaybe<Scalars['String']['input']>;
  quienesDesc2?: InputMaybe<Scalars['String']['input']>;
  quienesImagen?: InputMaybe<Scalars['String']['input']>;
  statProyectos?: InputMaybe<Scalars['String']['input']>;
  statSatisfaccion?: InputMaybe<Scalars['String']['input']>;
  statAnios?: InputMaybe<Scalars['String']['input']>;
  misionTitulo?: InputMaybe<Scalars['String']['input']>;
  misionDesc?: InputMaybe<Scalars['String']['input']>;
  visionTitulo?: InputMaybe<Scalars['String']['input']>;
  visionDesc?: InputMaybe<Scalars['String']['input']>;
  equipoSubtitulo?: InputMaybe<Scalars['String']['input']>;
  porqueTag?: InputMaybe<Scalars['String']['input']>;
  porqueTitulo?: InputMaybe<Scalars['String']['input']>;
  porqueSubtitulo?: InputMaybe<Scalars['String']['input']>;
  porqueItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  teamMembers?: InputMaybe<Array<InputMaybe<NosotrosTeamMembersMutation>>>;
};

export type LegalPrivacidadBloquesMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  contenido?: InputMaybe<Scalars['String']['input']>;
};

export type LegalPrivacidadMutation = {
  bloques?: InputMaybe<Array<InputMaybe<LegalPrivacidadBloquesMutation>>>;
};

export type LegalCookiesBloquesMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  contenido?: InputMaybe<Scalars['String']['input']>;
};

export type LegalCookiesMutation = {
  bloques?: InputMaybe<Array<InputMaybe<LegalCookiesBloquesMutation>>>;
};

export type LegalTerminosBloquesMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  contenido?: InputMaybe<Scalars['String']['input']>;
};

export type LegalTerminosMutation = {
  bloques?: InputMaybe<Array<InputMaybe<LegalTerminosBloquesMutation>>>;
};

export type LegalMutation = {
  privacidad?: InputMaybe<LegalPrivacidadMutation>;
  cookies?: InputMaybe<LegalCookiesMutation>;
  terminos?: InputMaybe<LegalTerminosMutation>;
};

export type ContactoMutation = {
  panelTag?: InputMaybe<Scalars['String']['input']>;
  panelTitulo?: InputMaybe<Scalars['String']['input']>;
  panelDescripcion?: InputMaybe<Scalars['String']['input']>;
  panelItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  email?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
  direccion?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigPartsFragment = { __typename: 'Config', logo?: string | null, heroImagenes?: Array<string | null> | null, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null };

export type FooterPartsFragment = { __typename: 'Footer', descripcion?: string | null, copyright?: string | null, facebook?: string | null, serviciosLinks?: Array<{ __typename: 'FooterServiciosLinks', label?: string | null, href?: string | null } | null> | null, empresaLinks?: Array<{ __typename: 'FooterEmpresaLinks', label?: string | null, href?: string | null } | null> | null, legalLinksIzquierda?: Array<{ __typename: 'FooterLegalLinksIzquierda', label?: string | null, href?: string | null } | null> | null, legalLinksDerecha?: Array<{ __typename: 'FooterLegalLinksDerecha', label?: string | null, href?: string | null } | null> | null };

export type HomePartsFragment = { __typename: 'Home', propuestaTag?: string | null, propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueHeader?: string | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoHeader?: string | null, procesoSubtitulo?: string | null, innovacionHeader?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null };

export type ServiciosPartsFragment = { __typename: 'Servicios', introTitulo?: string | null, introSubtitulo?: string | null, introDesc?: string | null, introPorqueTitulo?: string | null, introPorqueSubtitulo?: string | null, introPorqueDesc?: string | null, nuestrosServiciosTitulo?: string | null, nuestrosServiciosSubtitulo?: string | null, integralTitulo?: string | null, integralSubtitulo?: string | null, integralImagenPrincipal?: string | null, herramientasTitulo?: string | null, herramientasSubtitulo?: string | null, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null };

export type NosotrosPartsFragment = { __typename: 'Nosotros', quienesTag?: string | null, quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, equipoSubtitulo?: string | null, porqueTag?: string | null, porqueTitulo?: string | null, porqueSubtitulo?: string | null, porqueItems?: Array<string | null> | null, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null, linkedin?: string | null } | null> | null };

export type LegalPartsFragment = { __typename: 'Legal', privacidad?: { __typename: 'LegalPrivacidad', bloques?: Array<{ __typename: 'LegalPrivacidadBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, cookies?: { __typename: 'LegalCookies', bloques?: Array<{ __typename: 'LegalCookiesBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, terminos?: { __typename: 'LegalTerminos', bloques?: Array<{ __typename: 'LegalTerminosBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null };

export type ContactoPartsFragment = { __typename: 'Contacto', panelTag?: string | null, panelTitulo?: string | null, panelDescripcion?: string | null, panelItems?: Array<string | null> | null, email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null };

export type ConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigQuery = { __typename?: 'Query', config: { __typename: 'Config', id: string, logo?: string | null, heroImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null } };

export type ConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
}>;


export type ConfigConnectionQuery = { __typename?: 'Query', configConnection: { __typename?: 'ConfigConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigConnectionEdges', cursor: string, node?: { __typename: 'Config', id: string, logo?: string | null, heroImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, descripcion?: string | null, copyright?: string | null, facebook?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviciosLinks?: Array<{ __typename: 'FooterServiciosLinks', label?: string | null, href?: string | null } | null> | null, empresaLinks?: Array<{ __typename: 'FooterEmpresaLinks', label?: string | null, href?: string | null } | null> | null, legalLinksIzquierda?: Array<{ __typename: 'FooterLegalLinksIzquierda', label?: string | null, href?: string | null } | null> | null, legalLinksDerecha?: Array<{ __typename: 'FooterLegalLinksDerecha', label?: string | null, href?: string | null } | null> | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, descripcion?: string | null, copyright?: string | null, facebook?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviciosLinks?: Array<{ __typename: 'FooterServiciosLinks', label?: string | null, href?: string | null } | null> | null, empresaLinks?: Array<{ __typename: 'FooterEmpresaLinks', label?: string | null, href?: string | null } | null> | null, legalLinksIzquierda?: Array<{ __typename: 'FooterLegalLinksIzquierda', label?: string | null, href?: string | null } | null> | null, legalLinksDerecha?: Array<{ __typename: 'FooterLegalLinksDerecha', label?: string | null, href?: string | null } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, propuestaTag?: string | null, propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueHeader?: string | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoHeader?: string | null, procesoSubtitulo?: string | null, innovacionHeader?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, propuestaTag?: string | null, propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueHeader?: string | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoHeader?: string | null, procesoSubtitulo?: string | null, innovacionHeader?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null } | null } | null> | null } };

export type ServiciosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiciosQuery = { __typename?: 'Query', servicios: { __typename: 'Servicios', id: string, introTitulo?: string | null, introSubtitulo?: string | null, introDesc?: string | null, introPorqueTitulo?: string | null, introPorqueSubtitulo?: string | null, introPorqueDesc?: string | null, nuestrosServiciosTitulo?: string | null, nuestrosServiciosSubtitulo?: string | null, integralTitulo?: string | null, integralSubtitulo?: string | null, integralImagenPrincipal?: string | null, herramientasTitulo?: string | null, herramientasSubtitulo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null } };

export type ServiciosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
}>;


export type ServiciosConnectionQuery = { __typename?: 'Query', serviciosConnection: { __typename?: 'ServiciosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiciosConnectionEdges', cursor: string, node?: { __typename: 'Servicios', id: string, introTitulo?: string | null, introSubtitulo?: string | null, introDesc?: string | null, introPorqueTitulo?: string | null, introPorqueSubtitulo?: string | null, introPorqueDesc?: string | null, nuestrosServiciosTitulo?: string | null, nuestrosServiciosSubtitulo?: string | null, integralTitulo?: string | null, integralSubtitulo?: string | null, integralImagenPrincipal?: string | null, herramientasTitulo?: string | null, herramientasSubtitulo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null } | null } | null> | null } };

export type NosotrosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NosotrosQuery = { __typename?: 'Query', nosotros: { __typename: 'Nosotros', id: string, quienesTag?: string | null, quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, equipoSubtitulo?: string | null, porqueTag?: string | null, porqueTitulo?: string | null, porqueSubtitulo?: string | null, porqueItems?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null, linkedin?: string | null } | null> | null } };

export type NosotrosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NosotrosFilter>;
}>;


export type NosotrosConnectionQuery = { __typename?: 'Query', nosotrosConnection: { __typename?: 'NosotrosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NosotrosConnectionEdges', cursor: string, node?: { __typename: 'Nosotros', id: string, quienesTag?: string | null, quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, equipoSubtitulo?: string | null, porqueTag?: string | null, porqueTitulo?: string | null, porqueSubtitulo?: string | null, porqueItems?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null, linkedin?: string | null } | null> | null } | null } | null> | null } };

export type LegalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type LegalQuery = { __typename?: 'Query', legal: { __typename: 'Legal', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, privacidad?: { __typename: 'LegalPrivacidad', bloques?: Array<{ __typename: 'LegalPrivacidadBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, cookies?: { __typename: 'LegalCookies', bloques?: Array<{ __typename: 'LegalCookiesBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, terminos?: { __typename: 'LegalTerminos', bloques?: Array<{ __typename: 'LegalTerminosBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null } };

export type LegalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LegalFilter>;
}>;


export type LegalConnectionQuery = { __typename?: 'Query', legalConnection: { __typename?: 'LegalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'LegalConnectionEdges', cursor: string, node?: { __typename: 'Legal', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, privacidad?: { __typename: 'LegalPrivacidad', bloques?: Array<{ __typename: 'LegalPrivacidadBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, cookies?: { __typename: 'LegalCookies', bloques?: Array<{ __typename: 'LegalCookiesBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null, terminos?: { __typename: 'LegalTerminos', bloques?: Array<{ __typename: 'LegalTerminosBloques', titulo?: string | null, contenido?: string | null } | null> | null } | null } | null } | null> | null } };

export type ContactoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactoQuery = { __typename?: 'Query', contacto: { __typename: 'Contacto', id: string, panelTag?: string | null, panelTitulo?: string | null, panelDescripcion?: string | null, panelItems?: Array<string | null> | null, email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
}>;


export type ContactoConnectionQuery = { __typename?: 'Query', contactoConnection: { __typename?: 'ContactoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactoConnectionEdges', cursor: string, node?: { __typename: 'Contacto', id: string, panelTag?: string | null, panelTitulo?: string | null, panelDescripcion?: string | null, panelItems?: Array<string | null> | null, email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ConfigPartsFragmentDoc = gql`
    fragment ConfigParts on Config {
  __typename
  logo
  nav {
    __typename
    label
    href
  }
  heroHome {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroServicios {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroNosotros {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroContacto {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroImagenes
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  descripcion
  copyright
  facebook
  serviciosLinks {
    __typename
    label
    href
  }
  empresaLinks {
    __typename
    label
    href
  }
  legalLinksIzquierda {
    __typename
    label
    href
  }
  legalLinksDerecha {
    __typename
    label
    href
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  propuestaTag
  propuestaTitulo
  propuestaSubtitulo
  propuestaItems
  enfoqueHeader
  enfoqueSubtitulo
  enfoqueCards {
    __typename
    emoji
    titulo
    descripcion
  }
  crecimientoTitulo
  crecimientoSubtitulo
  crecimientoCards {
    __typename
    titulo
    descripcion
    imagenes
  }
  procesoHeader
  procesoSubtitulo
  procesoSteps {
    __typename
    titulo
    descripcion
  }
  innovacionHeader
  innovacionSubtitulo
  innovacionFeatures {
    __typename
    emoji
    titulo
    descripcion
  }
  innovacionImagenes
}
    `;
export const ServiciosPartsFragmentDoc = gql`
    fragment ServiciosParts on Servicios {
  __typename
  introTitulo
  introSubtitulo
  introDesc
  introPorqueTitulo
  introPorqueSubtitulo
  introPorqueDesc
  nuestrosServiciosTitulo
  nuestrosServiciosSubtitulo
  servicios {
    __typename
    titulo
    descripcion
    items
  }
  integralTitulo
  integralSubtitulo
  integralImagenPrincipal
  herramientasTitulo
  herramientasSubtitulo
  faqItems {
    __typename
    pregunta
    respuesta
  }
}
    `;
export const NosotrosPartsFragmentDoc = gql`
    fragment NosotrosParts on Nosotros {
  __typename
  quienesTag
  quienesTitulo
  quienesDesc1
  quienesDesc2
  quienesImagen
  statProyectos
  statSatisfaccion
  statAnios
  misionTitulo
  misionDesc
  visionTitulo
  visionDesc
  equipoSubtitulo
  porqueTag
  porqueTitulo
  porqueSubtitulo
  porqueItems
  teamMembers {
    __typename
    nombre
    rol
    descripcion
    foto
    linkedin
  }
}
    `;
export const LegalPartsFragmentDoc = gql`
    fragment LegalParts on Legal {
  __typename
  privacidad {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
  cookies {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
  terminos {
    __typename
    bloques {
      __typename
      titulo
      contenido
    }
  }
}
    `;
export const ContactoPartsFragmentDoc = gql`
    fragment ContactoParts on Contacto {
  __typename
  panelTag
  panelTitulo
  panelDescripcion
  panelItems
  email
  whatsapp
  direccion
  instagram
  linkedin
}
    `;
export const ConfigDocument = gql`
    query config($relativePath: String!) {
  config(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigParts
  }
}
    ${ConfigPartsFragmentDoc}`;
export const ConfigConnectionDocument = gql`
    query configConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigFilter) {
  configConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigParts
      }
    }
  }
}
    ${ConfigPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const ServiciosDocument = gql`
    query servicios($relativePath: String!) {
  servicios(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiciosParts
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const ServiciosConnectionDocument = gql`
    query serviciosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiciosFilter) {
  serviciosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiciosParts
      }
    }
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const NosotrosDocument = gql`
    query nosotros($relativePath: String!) {
  nosotros(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NosotrosParts
  }
}
    ${NosotrosPartsFragmentDoc}`;
export const NosotrosConnectionDocument = gql`
    query nosotrosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NosotrosFilter) {
  nosotrosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NosotrosParts
      }
    }
  }
}
    ${NosotrosPartsFragmentDoc}`;
export const LegalDocument = gql`
    query legal($relativePath: String!) {
  legal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LegalParts
  }
}
    ${LegalPartsFragmentDoc}`;
export const LegalConnectionDocument = gql`
    query legalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LegalFilter) {
  legalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LegalParts
      }
    }
  }
}
    ${LegalPartsFragmentDoc}`;
export const ContactoDocument = gql`
    query contacto($relativePath: String!) {
  contacto(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactoParts
  }
}
    ${ContactoPartsFragmentDoc}`;
export const ContactoConnectionDocument = gql`
    query contactoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactoFilter) {
  contactoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactoParts
      }
    }
  }
}
    ${ContactoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      config(variables: ConfigQueryVariables, options?: C): Promise<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}> {
        return requester<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}, ConfigQueryVariables>(ConfigDocument, variables, options);
      },
    configConnection(variables?: ConfigConnectionQueryVariables, options?: C): Promise<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}, ConfigConnectionQueryVariables>(ConfigConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    servicios(variables: ServiciosQueryVariables, options?: C): Promise<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}> {
        return requester<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}, ServiciosQueryVariables>(ServiciosDocument, variables, options);
      },
    serviciosConnection(variables?: ServiciosConnectionQueryVariables, options?: C): Promise<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}> {
        return requester<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}, ServiciosConnectionQueryVariables>(ServiciosConnectionDocument, variables, options);
      },
    nosotros(variables: NosotrosQueryVariables, options?: C): Promise<{data: NosotrosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosQueryVariables, query: string}> {
        return requester<{data: NosotrosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosQueryVariables, query: string}, NosotrosQueryVariables>(NosotrosDocument, variables, options);
      },
    nosotrosConnection(variables?: NosotrosConnectionQueryVariables, options?: C): Promise<{data: NosotrosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosConnectionQueryVariables, query: string}> {
        return requester<{data: NosotrosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosConnectionQueryVariables, query: string}, NosotrosConnectionQueryVariables>(NosotrosConnectionDocument, variables, options);
      },
    legal(variables: LegalQueryVariables, options?: C): Promise<{data: LegalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalQueryVariables, query: string}> {
        return requester<{data: LegalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalQueryVariables, query: string}, LegalQueryVariables>(LegalDocument, variables, options);
      },
    legalConnection(variables?: LegalConnectionQueryVariables, options?: C): Promise<{data: LegalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalConnectionQueryVariables, query: string}> {
        return requester<{data: LegalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LegalConnectionQueryVariables, query: string}, LegalConnectionQueryVariables>(LegalConnectionDocument, variables, options);
      },
    contacto(variables: ContactoQueryVariables, options?: C): Promise<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}> {
        return requester<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}, ContactoQueryVariables>(ContactoDocument, variables, options);
      },
    contactoConnection(variables?: ContactoConnectionQueryVariables, options?: C): Promise<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}> {
        return requester<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}, ContactoConnectionQueryVariables>(ContactoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/9d19bec7-8aea-435a-8adb-a081ce91aab9/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  