//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  config: Config;
  configConnection: ConfigConnection;
  home: Home;
  homeConnection: HomeConnection;
  servicios: Servicios;
  serviciosConnection: ServiciosConnection;
  nosotros: Nosotros;
  nosotrosConnection: NosotrosConnection;
  contacto: Contacto;
  contactoConnection: ContactoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryServiciosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiciosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
};


export type QueryNosotrosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNosotrosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NosotrosFilter>;
};


export type QueryContactoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
};

export type DocumentFilter = {
  config?: InputMaybe<ConfigFilter>;
  home?: InputMaybe<HomeFilter>;
  servicios?: InputMaybe<ServiciosFilter>;
  nosotros?: InputMaybe<NosotrosFilter>;
  contacto?: InputMaybe<ContactoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Config | Home | Servicios | Nosotros | Contacto | Folder;

export type ConfigNav = {
  __typename?: 'ConfigNav';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type ConfigHeroHome = {
  __typename?: 'ConfigHeroHome';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroServicios = {
  __typename?: 'ConfigHeroServicios';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroNosotros = {
  __typename?: 'ConfigHeroNosotros';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ConfigHeroContacto = {
  __typename?: 'ConfigHeroContacto';
  subtitulo?: Maybe<Scalars['String']['output']>;
  ctaTexto?: Maybe<Scalars['String']['output']>;
  pills?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type Config = Node & Document & {
  __typename?: 'Config';
  logo?: Maybe<Scalars['String']['output']>;
  nav?: Maybe<Array<Maybe<ConfigNav>>>;
  footerDescripcion?: Maybe<Scalars['String']['output']>;
  footerCopyright?: Maybe<Scalars['String']['output']>;
  heroHome?: Maybe<ConfigHeroHome>;
  heroServicios?: Maybe<ConfigHeroServicios>;
  heroNosotros?: Maybe<ConfigHeroNosotros>;
  heroContacto?: Maybe<ConfigHeroContacto>;
  heroImagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigNavFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type ConfigHeroHomeFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroServiciosFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroNosotrosFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigHeroContactoFilter = {
  subtitulo?: InputMaybe<StringFilter>;
  ctaTexto?: InputMaybe<StringFilter>;
  pills?: InputMaybe<StringFilter>;
};

export type ConfigFilter = {
  logo?: InputMaybe<ImageFilter>;
  nav?: InputMaybe<ConfigNavFilter>;
  footerDescripcion?: InputMaybe<StringFilter>;
  footerCopyright?: InputMaybe<StringFilter>;
  heroHome?: InputMaybe<ConfigHeroHomeFilter>;
  heroServicios?: InputMaybe<ConfigHeroServiciosFilter>;
  heroNosotros?: InputMaybe<ConfigHeroNosotrosFilter>;
  heroContacto?: InputMaybe<ConfigHeroContactoFilter>;
  heroImagenes?: InputMaybe<ImageFilter>;
};

export type ConfigConnectionEdges = {
  __typename?: 'ConfigConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Config>;
};

export type ConfigConnection = Connection & {
  __typename?: 'ConfigConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfigConnectionEdges>>>;
};

export type HomeEnfoqueCards = {
  __typename?: 'HomeEnfoqueCards';
  emoji?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type HomeCrecimientoCards = {
  __typename?: 'HomeCrecimientoCards';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  imagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeProcesoSteps = {
  __typename?: 'HomeProcesoSteps';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type HomeInnovacionFeatures = {
  __typename?: 'HomeInnovacionFeatures';
  emoji?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  propuestaTitulo?: Maybe<Scalars['String']['output']>;
  propuestaSubtitulo?: Maybe<Scalars['String']['output']>;
  propuestaItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  enfoqueSubtitulo?: Maybe<Scalars['String']['output']>;
  enfoqueCards?: Maybe<Array<Maybe<HomeEnfoqueCards>>>;
  crecimientoTitulo?: Maybe<Scalars['String']['output']>;
  crecimientoSubtitulo?: Maybe<Scalars['String']['output']>;
  crecimientoCards?: Maybe<Array<Maybe<HomeCrecimientoCards>>>;
  procesoSubtitulo?: Maybe<Scalars['String']['output']>;
  procesoSteps?: Maybe<Array<Maybe<HomeProcesoSteps>>>;
  innovacionSubtitulo?: Maybe<Scalars['String']['output']>;
  innovacionFeatures?: Maybe<Array<Maybe<HomeInnovacionFeatures>>>;
  innovacionImagenes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeEnfoqueCardsFilter = {
  emoji?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeCrecimientoCardsFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  imagenes?: InputMaybe<ImageFilter>;
};

export type HomeProcesoStepsFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeInnovacionFeaturesFilter = {
  emoji?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  propuestaTitulo?: InputMaybe<StringFilter>;
  propuestaSubtitulo?: InputMaybe<StringFilter>;
  propuestaItems?: InputMaybe<StringFilter>;
  enfoqueSubtitulo?: InputMaybe<StringFilter>;
  enfoqueCards?: InputMaybe<HomeEnfoqueCardsFilter>;
  crecimientoTitulo?: InputMaybe<StringFilter>;
  crecimientoSubtitulo?: InputMaybe<StringFilter>;
  crecimientoCards?: InputMaybe<HomeCrecimientoCardsFilter>;
  procesoSubtitulo?: InputMaybe<StringFilter>;
  procesoSteps?: InputMaybe<HomeProcesoStepsFilter>;
  innovacionSubtitulo?: InputMaybe<StringFilter>;
  innovacionFeatures?: InputMaybe<HomeInnovacionFeaturesFilter>;
  innovacionImagenes?: InputMaybe<ImageFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type ServiciosServicios = {
  __typename?: 'ServiciosServicios';
  titulo?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ServiciosFaqItems = {
  __typename?: 'ServiciosFaqItems';
  pregunta?: Maybe<Scalars['String']['output']>;
  respuesta?: Maybe<Scalars['String']['output']>;
};

export type Servicios = Node & Document & {
  __typename?: 'Servicios';
  servicios?: Maybe<Array<Maybe<ServiciosServicios>>>;
  integralImagenPrincipal?: Maybe<Scalars['String']['output']>;
  faqItems?: Maybe<Array<Maybe<ServiciosFaqItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiciosServiciosFilter = {
  titulo?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type ServiciosFaqItemsFilter = {
  pregunta?: InputMaybe<StringFilter>;
  respuesta?: InputMaybe<StringFilter>;
};

export type ServiciosFilter = {
  servicios?: InputMaybe<ServiciosServiciosFilter>;
  integralImagenPrincipal?: InputMaybe<ImageFilter>;
  faqItems?: InputMaybe<ServiciosFaqItemsFilter>;
};

export type ServiciosConnectionEdges = {
  __typename?: 'ServiciosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Servicios>;
};

export type ServiciosConnection = Connection & {
  __typename?: 'ServiciosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiciosConnectionEdges>>>;
};

export type NosotrosTeamMembers = {
  __typename?: 'NosotrosTeamMembers';
  nombre?: Maybe<Scalars['String']['output']>;
  rol?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
};

export type Nosotros = Node & Document & {
  __typename?: 'Nosotros';
  quienesTitulo?: Maybe<Scalars['String']['output']>;
  quienesDesc1?: Maybe<Scalars['String']['output']>;
  quienesDesc2?: Maybe<Scalars['String']['output']>;
  quienesImagen?: Maybe<Scalars['String']['output']>;
  statProyectos?: Maybe<Scalars['String']['output']>;
  statSatisfaccion?: Maybe<Scalars['String']['output']>;
  statAnios?: Maybe<Scalars['String']['output']>;
  misionTitulo?: Maybe<Scalars['String']['output']>;
  misionDesc?: Maybe<Scalars['String']['output']>;
  visionTitulo?: Maybe<Scalars['String']['output']>;
  visionDesc?: Maybe<Scalars['String']['output']>;
  porqueItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  teamMembers?: Maybe<Array<Maybe<NosotrosTeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NosotrosTeamMembersFilter = {
  nombre?: InputMaybe<StringFilter>;
  rol?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
};

export type NosotrosFilter = {
  quienesTitulo?: InputMaybe<StringFilter>;
  quienesDesc1?: InputMaybe<StringFilter>;
  quienesDesc2?: InputMaybe<StringFilter>;
  quienesImagen?: InputMaybe<ImageFilter>;
  statProyectos?: InputMaybe<StringFilter>;
  statSatisfaccion?: InputMaybe<StringFilter>;
  statAnios?: InputMaybe<StringFilter>;
  misionTitulo?: InputMaybe<StringFilter>;
  misionDesc?: InputMaybe<StringFilter>;
  visionTitulo?: InputMaybe<StringFilter>;
  visionDesc?: InputMaybe<StringFilter>;
  porqueItems?: InputMaybe<StringFilter>;
  teamMembers?: InputMaybe<NosotrosTeamMembersFilter>;
};

export type NosotrosConnectionEdges = {
  __typename?: 'NosotrosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Nosotros>;
};

export type NosotrosConnection = Connection & {
  __typename?: 'NosotrosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NosotrosConnectionEdges>>>;
};

export type Contacto = Node & Document & {
  __typename?: 'Contacto';
  email?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  direccion?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactoFilter = {
  email?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
  direccion?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type ContactoConnectionEdges = {
  __typename?: 'ContactoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacto>;
};

export type ContactoConnection = Connection & {
  __typename?: 'ContactoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConfig: Config;
  createConfig: Config;
  updateHome: Home;
  createHome: Home;
  updateServicios: Servicios;
  createServicios: Servicios;
  updateNosotros: Nosotros;
  createNosotros: Nosotros;
  updateContacto: Contacto;
  createContacto: Contacto;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationCreateConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfigMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationCreateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationUpdateNosotrosArgs = {
  relativePath: Scalars['String']['input'];
  params: NosotrosMutation;
};


export type MutationCreateNosotrosArgs = {
  relativePath: Scalars['String']['input'];
  params: NosotrosMutation;
};


export type MutationUpdateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};


export type MutationCreateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};

export type DocumentUpdateMutation = {
  config?: InputMaybe<ConfigMutation>;
  home?: InputMaybe<HomeMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  nosotros?: InputMaybe<NosotrosMutation>;
  contacto?: InputMaybe<ContactoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  config?: InputMaybe<ConfigMutation>;
  home?: InputMaybe<HomeMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  nosotros?: InputMaybe<NosotrosMutation>;
  contacto?: InputMaybe<ContactoMutation>;
};

export type ConfigNavMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigHeroHomeMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroServiciosMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroNosotrosMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigHeroContactoMutation = {
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  ctaTexto?: InputMaybe<Scalars['String']['input']>;
  pills?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfigMutation = {
  logo?: InputMaybe<Scalars['String']['input']>;
  nav?: InputMaybe<Array<InputMaybe<ConfigNavMutation>>>;
  footerDescripcion?: InputMaybe<Scalars['String']['input']>;
  footerCopyright?: InputMaybe<Scalars['String']['input']>;
  heroHome?: InputMaybe<ConfigHeroHomeMutation>;
  heroServicios?: InputMaybe<ConfigHeroServiciosMutation>;
  heroNosotros?: InputMaybe<ConfigHeroNosotrosMutation>;
  heroContacto?: InputMaybe<ConfigHeroContactoMutation>;
  heroImagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeEnfoqueCardsMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeCrecimientoCardsMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  imagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeProcesoStepsMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeInnovacionFeaturesMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  propuestaTitulo?: InputMaybe<Scalars['String']['input']>;
  propuestaSubtitulo?: InputMaybe<Scalars['String']['input']>;
  propuestaItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  enfoqueSubtitulo?: InputMaybe<Scalars['String']['input']>;
  enfoqueCards?: InputMaybe<Array<InputMaybe<HomeEnfoqueCardsMutation>>>;
  crecimientoTitulo?: InputMaybe<Scalars['String']['input']>;
  crecimientoSubtitulo?: InputMaybe<Scalars['String']['input']>;
  crecimientoCards?: InputMaybe<Array<InputMaybe<HomeCrecimientoCardsMutation>>>;
  procesoSubtitulo?: InputMaybe<Scalars['String']['input']>;
  procesoSteps?: InputMaybe<Array<InputMaybe<HomeProcesoStepsMutation>>>;
  innovacionSubtitulo?: InputMaybe<Scalars['String']['input']>;
  innovacionFeatures?: InputMaybe<Array<InputMaybe<HomeInnovacionFeaturesMutation>>>;
  innovacionImagenes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiciosServiciosMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServiciosFaqItemsMutation = {
  pregunta?: InputMaybe<Scalars['String']['input']>;
  respuesta?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosMutation = {
  servicios?: InputMaybe<Array<InputMaybe<ServiciosServiciosMutation>>>;
  integralImagenPrincipal?: InputMaybe<Scalars['String']['input']>;
  faqItems?: InputMaybe<Array<InputMaybe<ServiciosFaqItemsMutation>>>;
};

export type NosotrosTeamMembersMutation = {
  nombre?: InputMaybe<Scalars['String']['input']>;
  rol?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
};

export type NosotrosMutation = {
  quienesTitulo?: InputMaybe<Scalars['String']['input']>;
  quienesDesc1?: InputMaybe<Scalars['String']['input']>;
  quienesDesc2?: InputMaybe<Scalars['String']['input']>;
  quienesImagen?: InputMaybe<Scalars['String']['input']>;
  statProyectos?: InputMaybe<Scalars['String']['input']>;
  statSatisfaccion?: InputMaybe<Scalars['String']['input']>;
  statAnios?: InputMaybe<Scalars['String']['input']>;
  misionTitulo?: InputMaybe<Scalars['String']['input']>;
  misionDesc?: InputMaybe<Scalars['String']['input']>;
  visionTitulo?: InputMaybe<Scalars['String']['input']>;
  visionDesc?: InputMaybe<Scalars['String']['input']>;
  porqueItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  teamMembers?: InputMaybe<Array<InputMaybe<NosotrosTeamMembersMutation>>>;
};

export type ContactoMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
  direccion?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type ConfigPartsFragment = { __typename: 'Config', logo?: string | null, footerDescripcion?: string | null, footerCopyright?: string | null, heroImagenes?: Array<string | null> | null, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null };

export type HomePartsFragment = { __typename: 'Home', propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoSubtitulo?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null };

export type ServiciosPartsFragment = { __typename: 'Servicios', integralImagenPrincipal?: string | null, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null };

export type NosotrosPartsFragment = { __typename: 'Nosotros', quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, porqueItems?: Array<string | null> | null, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null } | null> | null };

export type ContactoPartsFragment = { __typename: 'Contacto', email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null };

export type ConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConfigQuery = { __typename?: 'Query', config: { __typename: 'Config', id: string, logo?: string | null, footerDescripcion?: string | null, footerCopyright?: string | null, heroImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null } };

export type ConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfigFilter>;
}>;


export type ConfigConnectionQuery = { __typename?: 'Query', configConnection: { __typename?: 'ConfigConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConfigConnectionEdges', cursor: string, node?: { __typename: 'Config', id: string, logo?: string | null, footerDescripcion?: string | null, footerCopyright?: string | null, heroImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: Array<{ __typename: 'ConfigNav', label?: string | null, href?: string | null } | null> | null, heroHome?: { __typename: 'ConfigHeroHome', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroServicios?: { __typename: 'ConfigHeroServicios', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroNosotros?: { __typename: 'ConfigHeroNosotros', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null, heroContacto?: { __typename: 'ConfigHeroContacto', subtitulo?: string | null, ctaTexto?: string | null, pills?: Array<string | null> | null } | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoSubtitulo?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, propuestaTitulo?: string | null, propuestaSubtitulo?: string | null, propuestaItems?: Array<string | null> | null, enfoqueSubtitulo?: string | null, crecimientoTitulo?: string | null, crecimientoSubtitulo?: string | null, procesoSubtitulo?: string | null, innovacionSubtitulo?: string | null, innovacionImagenes?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, enfoqueCards?: Array<{ __typename: 'HomeEnfoqueCards', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null, crecimientoCards?: Array<{ __typename: 'HomeCrecimientoCards', titulo?: string | null, descripcion?: string | null, imagenes?: Array<string | null> | null } | null> | null, procesoSteps?: Array<{ __typename: 'HomeProcesoSteps', titulo?: string | null, descripcion?: string | null } | null> | null, innovacionFeatures?: Array<{ __typename: 'HomeInnovacionFeatures', emoji?: string | null, titulo?: string | null, descripcion?: string | null } | null> | null } | null } | null> | null } };

export type ServiciosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiciosQuery = { __typename?: 'Query', servicios: { __typename: 'Servicios', id: string, integralImagenPrincipal?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null } };

export type ServiciosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
}>;


export type ServiciosConnectionQuery = { __typename?: 'Query', serviciosConnection: { __typename?: 'ServiciosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiciosConnectionEdges', cursor: string, node?: { __typename: 'Servicios', id: string, integralImagenPrincipal?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicios?: Array<{ __typename: 'ServiciosServicios', titulo?: string | null, descripcion?: string | null, items?: Array<string | null> | null } | null> | null, faqItems?: Array<{ __typename: 'ServiciosFaqItems', pregunta?: string | null, respuesta?: string | null } | null> | null } | null } | null> | null } };

export type NosotrosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NosotrosQuery = { __typename?: 'Query', nosotros: { __typename: 'Nosotros', id: string, quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, porqueItems?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null } | null> | null } };

export type NosotrosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NosotrosFilter>;
}>;


export type NosotrosConnectionQuery = { __typename?: 'Query', nosotrosConnection: { __typename?: 'NosotrosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NosotrosConnectionEdges', cursor: string, node?: { __typename: 'Nosotros', id: string, quienesTitulo?: string | null, quienesDesc1?: string | null, quienesDesc2?: string | null, quienesImagen?: string | null, statProyectos?: string | null, statSatisfaccion?: string | null, statAnios?: string | null, misionTitulo?: string | null, misionDesc?: string | null, visionTitulo?: string | null, visionDesc?: string | null, porqueItems?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, teamMembers?: Array<{ __typename: 'NosotrosTeamMembers', nombre?: string | null, rol?: string | null, descripcion?: string | null, foto?: string | null } | null> | null } | null } | null> | null } };

export type ContactoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactoQuery = { __typename?: 'Query', contacto: { __typename: 'Contacto', id: string, email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
}>;


export type ContactoConnectionQuery = { __typename?: 'Query', contactoConnection: { __typename?: 'ContactoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactoConnectionEdges', cursor: string, node?: { __typename: 'Contacto', id: string, email?: string | null, whatsapp?: string | null, direccion?: string | null, instagram?: string | null, linkedin?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ConfigPartsFragmentDoc = gql`
    fragment ConfigParts on Config {
  __typename
  logo
  nav {
    __typename
    label
    href
  }
  footerDescripcion
  footerCopyright
  heroHome {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroServicios {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroNosotros {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroContacto {
    __typename
    subtitulo
    ctaTexto
    pills
  }
  heroImagenes
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  propuestaTitulo
  propuestaSubtitulo
  propuestaItems
  enfoqueSubtitulo
  enfoqueCards {
    __typename
    emoji
    titulo
    descripcion
  }
  crecimientoTitulo
  crecimientoSubtitulo
  crecimientoCards {
    __typename
    titulo
    descripcion
    imagenes
  }
  procesoSubtitulo
  procesoSteps {
    __typename
    titulo
    descripcion
  }
  innovacionSubtitulo
  innovacionFeatures {
    __typename
    emoji
    titulo
    descripcion
  }
  innovacionImagenes
}
    `;
export const ServiciosPartsFragmentDoc = gql`
    fragment ServiciosParts on Servicios {
  __typename
  servicios {
    __typename
    titulo
    descripcion
    items
  }
  integralImagenPrincipal
  faqItems {
    __typename
    pregunta
    respuesta
  }
}
    `;
export const NosotrosPartsFragmentDoc = gql`
    fragment NosotrosParts on Nosotros {
  __typename
  quienesTitulo
  quienesDesc1
  quienesDesc2
  quienesImagen
  statProyectos
  statSatisfaccion
  statAnios
  misionTitulo
  misionDesc
  visionTitulo
  visionDesc
  porqueItems
  teamMembers {
    __typename
    nombre
    rol
    descripcion
    foto
  }
}
    `;
export const ContactoPartsFragmentDoc = gql`
    fragment ContactoParts on Contacto {
  __typename
  email
  whatsapp
  direccion
  instagram
  linkedin
}
    `;
export const ConfigDocument = gql`
    query config($relativePath: String!) {
  config(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfigParts
  }
}
    ${ConfigPartsFragmentDoc}`;
export const ConfigConnectionDocument = gql`
    query configConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfigFilter) {
  configConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfigParts
      }
    }
  }
}
    ${ConfigPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const ServiciosDocument = gql`
    query servicios($relativePath: String!) {
  servicios(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiciosParts
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const ServiciosConnectionDocument = gql`
    query serviciosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiciosFilter) {
  serviciosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiciosParts
      }
    }
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const NosotrosDocument = gql`
    query nosotros($relativePath: String!) {
  nosotros(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NosotrosParts
  }
}
    ${NosotrosPartsFragmentDoc}`;
export const NosotrosConnectionDocument = gql`
    query nosotrosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NosotrosFilter) {
  nosotrosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NosotrosParts
      }
    }
  }
}
    ${NosotrosPartsFragmentDoc}`;
export const ContactoDocument = gql`
    query contacto($relativePath: String!) {
  contacto(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactoParts
  }
}
    ${ContactoPartsFragmentDoc}`;
export const ContactoConnectionDocument = gql`
    query contactoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactoFilter) {
  contactoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactoParts
      }
    }
  }
}
    ${ContactoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      config(variables: ConfigQueryVariables, options?: C): Promise<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}> {
        return requester<{data: ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigQueryVariables, query: string}, ConfigQueryVariables>(ConfigDocument, variables, options);
      },
    configConnection(variables?: ConfigConnectionQueryVariables, options?: C): Promise<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}> {
        return requester<{data: ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfigConnectionQueryVariables, query: string}, ConfigConnectionQueryVariables>(ConfigConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    servicios(variables: ServiciosQueryVariables, options?: C): Promise<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}> {
        return requester<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}, ServiciosQueryVariables>(ServiciosDocument, variables, options);
      },
    serviciosConnection(variables?: ServiciosConnectionQueryVariables, options?: C): Promise<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}> {
        return requester<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}, ServiciosConnectionQueryVariables>(ServiciosConnectionDocument, variables, options);
      },
    nosotros(variables: NosotrosQueryVariables, options?: C): Promise<{data: NosotrosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosQueryVariables, query: string}> {
        return requester<{data: NosotrosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosQueryVariables, query: string}, NosotrosQueryVariables>(NosotrosDocument, variables, options);
      },
    nosotrosConnection(variables?: NosotrosConnectionQueryVariables, options?: C): Promise<{data: NosotrosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosConnectionQueryVariables, query: string}> {
        return requester<{data: NosotrosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NosotrosConnectionQueryVariables, query: string}, NosotrosConnectionQueryVariables>(NosotrosConnectionDocument, variables, options);
      },
    contacto(variables: ContactoQueryVariables, options?: C): Promise<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}> {
        return requester<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}, ContactoQueryVariables>(ContactoDocument, variables, options);
      },
    contactoConnection(variables?: ContactoConnectionQueryVariables, options?: C): Promise<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}> {
        return requester<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}, ContactoConnectionQueryVariables>(ContactoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  